export const ROLES = {
  OWNER: 'OWNER',
  ADMIN: 'ADMIN',
  MANAGER: 'MANAGER',
  EMPLOYEE: 'EMPLOYEE',
};

export const ALL_ROLES = [ROLES.OWNER, ROLES.ADMIN, ROLES.MANAGER, ROLES.EMPLOYEE];

export const MANAGER_AND_ABOVE = [ROLES.OWNER, ROLES.ADMIN, ROLES.MANAGER];
export const ADMIN_AND_ABOVE = [ROLES.OWNER, ROLES.ADMIN];
